### ISSUE TITLE
Temporary Redirect loads a blank page

### ISSUE THREAD

**Issue by ghost** [Amukerd/SparXSS#1]
I put any url in temporary redirect and it failed, loading a blank page instead.
However, the hyperlink page still works and using window.open in the js console also works fine

**Comment by ghost** [comment]
![Screenshot 2023-10-23 1 38 05 PM](https://github.com/Amukerd/SparXSS/assets/95651912/78b9885e-7193-4f4c-bc40-56e81c2d267f)
![Screenshot 2023-10-23 1 37 57 PM](https://github.com/Amukerd/SparXSS/assets/95651912/95e2f8c5-e0e2-4020-9b7f-fb652f6c4371)

**Comment by amukerd** [comment]
i kinda mess around with the main script a lot, but it should be functional right now
